### ISSUE TITLE
可提供激素替代治疗的医院或医生

### ISSUE THREAD

**Issue by FenXiu** [dy-octa/chinese-transgender-medical-resources#1]
上海瑞金医院仅有“性腺专病”门诊可进行激素替代治疗咨询，而且大多数的时候只有孙首悦一位医师出诊，普通内分泌科门诊不开激素药物
（瑞金的推荐抗雄为达英35，医院药房无国色，但是可开外配处方

**Comment by dy-octa** [comment]
好的~谢谢你的消息~
